from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib import colors
from backend.models.exam import PlacedQuestion, ExamStructure
from typing import List
import os

class PDFService:
    @staticmethod
    def render_exam_pdf(
        placed_questions: List[PlacedQuestion],
        structure: ExamStructure,
        output_path: str = "generated_exam.pdf"
    ) -> str:
        """
        Generates a structure-aware PDF exam.
        """
        print(f"Generating PDF at {output_path} with {len(placed_questions)} questions...")
        if not placed_questions:
            print("WARNING: No questions to render!")
            
        c = canvas.Canvas(output_path, pagesize=A4)
        width, height = A4
        y = height - 1.0 * inch
        
        # --- Header ---
        c.setFont("Helvetica-Bold", 16)
        c.drawCentredString(width / 2, y, "EduSynth Mock Examination")
        y -= 0.3 * inch
        c.setFont("Helvetica", 12)
        c.drawCentredString(width / 2, y, "Generated by AI Examiner Agent")
        y -= 0.5 * inch
        
        # Group questions by Unit
        questions_by_unit = {}
        for q in placed_questions:
            if q.unit_no not in questions_by_unit:
                questions_by_unit[q.unit_no] = {"A": [], "B": []}
            questions_by_unit[q.unit_no][q.main_choice].append(q)
            
        # --- Render Units ---
        for unit_no in sorted(questions_by_unit.keys()):
            unit_data = questions_by_unit[unit_no]
            
            # Check page break space (need approx 3 inches for a unit)
            if y < 3.0 * inch:
                c.showPage()
                y = height - 1.0 * inch
                
            # UNIT Header
            c.setFont("Helvetica-Bold", 14)
            c.drawCentredString(width / 2, y, f"UNIT - {unit_no}")
            y -= 0.4 * inch
            
            # Helper to render a choice block
            def render_block(questions, start_q_num):
                nonlocal y
                for q in questions:
                    if y < 1.0 * inch:
                        c.showPage()
                        y = height - 1.0 * inch
                        
                    # Main Q number only for first sub-question? 
                    # Usually "1. a) ... b) ..." 
                    # But data model has flattened questions. 
                    # Let's do: "1. (a) Text (Marks)"
                    
                    # Q Label: "1. (a)"
                    q_label = f"{start_q_num}. ({q.sub_label})"
                    
                    c.setFont("Helvetica", 11)
                    c.drawString(0.8 * inch, y, q_label)
                    
                    # Question Text (wrap)
                    text_obj = c.beginText(1.5 * inch, y)
                    text_obj.setFont("Helvetica", 11)
                    
                    # Wrap text simplistic
                    words = q.text.split()
                    line = ""
                    for word in words:
                        if c.stringWidth(line + " " + word, "Helvetica", 11) < 5.5 * inch:
                            line += " " + word
                        else:
                            text_obj.textLine(line)
                            line = word
                    text_obj.textLine(line)
                    c.drawText(text_obj)
                    
                    # Marks logic (aligned right roughly)
                    c.drawRightString(width - 0.8 * inch, y, f"({q.marks})")
                    
                    # Decrement y based on lines
                    num_lines = len(list(text_obj.getStartOfLine())) or 1 # Fallback
                    # textLine moves cursor down, but we need to track Y manually for reportlab canvas
                    # Rough estimate: 12 points per line
                    text_height = (c.stringWidth(q.text, "Helvetica", 11) / (5.5 * inch)) * 14 + 14
                    y -= text_height
                    
                    # Citation
                    c.setFont("Helvetica-Oblique", 9)
                    c.setFillColor(colors.grey)
                    c.drawString(1.5 * inch, y, f"Ref: {q.source_file}")
                    c.setFillColor(colors.black)
                    y -= 0.3 * inch

            # Choice A
            # Calculate Question Number: Unit 1 -> Q1, Unit 2 -> Q3 (if 2 questions per unit? 
            # Pattern varies. Let's assume Unit N uses Question No N? 
            # Or usually Unit 1 is Q1 or Q2. 
            # Let's map Unit 1 -> Q1/Q2, Unit 2 -> Q3/Q4.
            q_num_a = (unit_no * 2) - 1
            q_num_b = unit_no * 2
            
            # Actually, standard pattern: 
            # Unit 1: Q1 (with a,b,c) OR Q2 (with a,b,c).
            
            # Block A
            render_block(unit_data["A"], q_num_a)
            
            if structure.has_or_choice and unit_data["B"]:
                # OR Separator
                if y < 0.5 * inch:
                    c.showPage()
                    y = height - 1.0 * inch
                y -= 0.1 * inch
                c.setFont("Helvetica-Bold", 12)
                c.drawCentredString(width / 2, y, "OR")
                y -= 0.3 * inch
                
                # Block B
                render_block(unit_data["B"], q_num_b)
                
            y -= 0.4 * inch # Frequency between units
            
        c.save()
        return os.path.abspath(output_path)
